### ISSUE TITLE
returning array of section headers and section count

### ISSUE THREAD

**Issue by c-nv-s** [bitnami/ini-file#27]
### What is the problem this feature will solve?

given any "blackbox" .ini file, the tool will be able to return an array of all the section headers and a count of the number of sections

### What is the feature you are proposing to solve the problem?

add capability to return:
1. count of the number of sections in the .ini file
2. array of the section headers for further iteration in bash

### What alternatives have you considered?

none

**Comment by c-nv-s** [comment]
would also probably be useful if instead of showing an error if the user provides the ``--section`` flag but no ``--key`` flag, to actually return a list of the keys (or keys and values)  of the specified section.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by donaald795** [comment]
Thanks fo[r thos solution. [My Indigo Card](https://www-indigocard.com)

**Comment by c-nv-s** [comment]
thanks
