### ISSUE TITLE
The tool doesn't handle line comments

### ISSUE THREAD

**Issue by olipo186** [bitnami/ini-file#5]
Hi!

When the input file has commented out attributes, the file gets messed up after using `ini-file`.

**Input file:**
```
[Global]
;proxy_client_headers[] = HTTP_X_FORWARDED_FOR
```
**Command:**
```
ini-file set --section "General" --key "proxy_client_headers[]" --value "HTTP_X_FORWARDED_FOR" /path/to/file
```
**Expected result (either this):**
```
[Global]
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
```
**Expected result (or something like this):**
```
[Global]
;proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
```
**Actual result:**
```
; ;proxy_client_headers[] = HTTP_X_FORWARDED_FOR
```

---------------------------------------------------------------
**Background info and use case**

I came in contact with this tool in my efforts to create a custom image based on `bitnami/matomo` and found a potential bug/feature request.

I wanted to do this:
> I needed to create a custom image based on `bitnami/matomo` with a custom Matomo configuration, since the configuration changes I desire cannot be configured using evironment variables (which are parsed by [libmatomo.sh](https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh)).

This is how I did it:
> Use the ini-file tool to manipulate `global.ini.php` while building a custom image based on `bitnami/matomo`.

Dockerfile:
```
FROM bitnami/matomo:4-debian-10 AS build-env
USER 0
RUN ini-file set --section "General" --key "proxy_client_headers[]" --value "HTTP_X_FORWARDED_FOR" /opt/bitnami/matomo/config/global.ini.php
USER 1001
EXPOSE 8080 8443
```

**Comment by alemorcuq** [comment]
Hi, @olipo186.

Thanks for reporting this, we will take a look. Just to be sure, running your commands I also get the line correctly printed, apart from the one you mentioned with two semicolons.

```
; ;proxy_client_headers[] = HTTP_X_FORWARDED_FOR
...
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
```

Is this your case as well?

**Comment by marcosbc** [comment]
Hi all, I'm going to close this issue due to inactivity but feel free to send a contribution if are open to contribute any related feature.
